### ISSUE TITLE
Does mem_ex_get_module work?

### ISSUE THREAD

**Issue by karliky** [rdbo/libmem#2] opened 2020-09-10 20:15 UTC
So, I'm working on adding Node.js bindings to this library to use it with JavaScript. 🚀 

While working on this I found something weird, looks like `mem_ex_get_module ` doesn't work:

```
    PID:                8020
    Process Name:       explorer.exe
    Process ID:         8020
    Module Name:
    Module Path:
    Module Base:        0000000000000000
    Module Size:        0000000000000000
    Module End:         0000000000000000
```

The first 3 lines are from `mem_ex_get_pid` and `mem_ex_get_process` and they do work fine 👍 . Then comes `process_mod_ex` and they look empty or filled with 0000000000000000. The process name I'm using it's `explorer.exe`

Here is the source code, which I copied from https://github.com/rdbo/libmem/blob/master/example/example.cpp:
```
	mem_pid_t pid_ex = mem_ex_get_pid(mem_string_new(PROCESS_NAME));
	tprint("PID:                %i", pid_ex);

	//-- Get Process Information
	mem_process_t process_ex = mem_ex_get_process(pid_ex);
	tprint("Process Name:       %s", mem_string_c_str(&process_ex.name));
	tprint("Process ID:         %i", process_ex.pid);

	//-- Get Process Module
	mem_module_t process_mod_ex = mem_ex_get_module(process_ex, mem_string_new(PROCESS_NAME));
	tprint("Module Name:        %s", mem_string_c_str(&process_mod_ex.name));
	tprint("Module Path:        %s", mem_string_c_str(&process_mod_ex.path));
	tprint("Module Base:        %p", process_mod_ex.base);
	tprint("Module Size:        %p", (mem_voidptr_t)process_mod_ex.size);
	tprint("Module End:         %p", process_mod_ex.end);
```

Am I doing something wrong? 🧑‍💻 

Here is the whole source code just in case it helps:
[bindings.txt](https://github.com/rdbo/libmem/files/5202762/bindings.txt)

**Comment by rdbo** [comment] 2020-09-10 20:56
Hmmm, there seems to be an issue. For some reason, it works with "example.exe" but doesn't seem to work with "explorer.exe". I'm taking a look at it.

**Comment by rdbo** [comment] 2020-09-10 21:16
This is weird. I figured the problem is that Windows is returning INVALID_HANDLE_VALUE on mem_ex_get_module when I ask for a snapshot of the process modules. The weird part is that it is only happening is specific processes. I tested some processes and most of them worked. I'll do some more research and this issue will probably be fixed on version 2.1 (the next update).

**Comment by rdbo** [comment] 2020-09-11 01:23
After some debugging, I noticed that the module loaded in Windows Explorer is "Explorer.EXE", which is different from "explorer.exe". Should've checked this hours ago.
This should work (make sure it is compiled on the same architecture as your explorer.exe):
`
	mem_pid_t pid_ex = mem_ex_get_pid(mem_string_new(MEM_STR("explorer.exe")));
	mem_process_t process_ex = mem_ex_get_process(pid_ex);
	mem_module_t process_mod_ex = mem_ex_get_module(process_ex, mem_string_new(MEM_STR("Explorer.EXE")));
`

**Closed** 2020-09-11 01:25 UTC

**Comment by karliky** [comment] 2020-09-11 08:06
What do you think of doing a to_upper_case operation here so the if handle all module names in uppercase to avoid this kind of issues? https://github.com/rdbo/libmem/blob/8d319f55c2bc8008e027e8b21ba271c0989fa4f4/libmem/libmem.c#L557

**Comment by rdbo** [comment] 2020-09-11 16:40
I have thought about this, in fact, I even have the "mem_string_to_lower" function that would do so. But before adding this, I'm going to check whether you can import modules with variation of upper/lower case. Like, importing "test.dll", "Test.dll", "test.DLL"...
If you're able to do that, then I'll not add this. Else, then I'm gonna implement that.

**Comment by rdbo** [comment] 2020-09-11 16:48
As to your other question on how to get the module name, you can use things like Process Hacker or Cheat Engine to get the module name. Though with Explorer, I only managed to see the actual module name through debugging. Process Hacker seems to be doing the "to_lower_case" method you said, as I saw explorer.exe instead of Explorer.EXE there. I think I'm going to expand the memory lib a little bit, adding things like "get_process_list" and "get_module_list" to avoid this doubts. It might take some time though, as I also have to make one for Linux.

**Comment by rdbo** [comment] 2020-09-11 17:08
I just tested it out, and I'm not gonna add the "mem_string_to_lower" for getting modules. Windows allows "test.dll", "TEST.dll", "test.DLL" to be loaded, so if I add it you won't be able to get the non-lowercase variations.
![dlls](https://user-images.githubusercontent.com/57117082/92953572-520ab200-f438-11ea-8cf5-cbf13fc5b4eb.PNG)

**Comment by karliky** [comment] 2020-09-12 11:08
Ok, that's fine, I Will make sure I can handle this situation. 👏

I'm doing this work here https://github.com/karliky/Crazymem just fyi ☺️ you can add It to the proyects made with libmem list if you want to

**Comment by rdbo** [comment] 2020-09-19 19:09
I added 'mem_ex_get_process_list', 'mem_ex_get_module_list' and 'mem_in_get_module_list', so now you are able to parse the processes and modules the way you want. Example (print all processes and all their respective modules):

```
#include "libmem/libmem.h"

int main()
{
    mem_process_list_t proc_list = mem_ex_get_process_list();
    for(mem_size_t i = 0; i < MEM_THISCALL(proc_list, length); i++)
    {
        mem_process_t process = MEM_THISCALL(proc_list, at, i);
        mem_module_list_t  mod_list  = mem_ex_get_module_list(process);

        printf("--%s\n", MEM_THISCALL(process.name, c_str));

        for(mem_size_t j = 0; j < MEM_THISCALL(mod_list, length); j++)
        {
            mem_module_t mod = MEM_THISCALL(mod_list, at, j);

            printf("---- %s\n", MEM_THISCALL(mod.name, c_str));
        }
    }

    getchar();

    return 0;
}
```

**Comment by karliky** [comment] 2020-09-20 19:27
That’s super cool, thank you so much, I will add them soon to the us version.

Also, can you give me an example of usage for `mem_ex_load_library(mem_process_t process, mem_lib_t lib) `? I’m not quite sure of how to create a mem_lib_t type.

**Comment by rdbo** [comment] 2020-09-20 20:28
mem_ex_load_library is used to force the target process to load a dynamic library.
You can define it like this:
```
mem_lib_t lib = mem_lib_init(); //Initialize the variable
lib.path = mem_string_new("path/to/library.dll"); //Define the path to the dynamic library
lib.mode = RTLD_LAZY; //Define the flags (Linux only)
```

**Comment by karliky** [comment] 2020-09-21 15:57
I've just implemented loadLibrary and mem_ex_get_process_list 👍 https://github.com/karliky/Crazymem/commit/638c4d0835a17a42678a34edf0db4cf95adc2dea

My Discord is `karliky (bugcraft)#4924`, just in case you have one, we can speak there
